### ISSUE TITLE
Submit Better Collada Exporter to the Blender devs for inclusion

### ISSUE THREAD

**Issue by ghost** [godotengine/collada-exporter#31]
(Continued from godotengine/godot#5457)

Alright, so [last time](https://developer.blender.org/D1787) the Better Collada Exporter was submitted to the Blender devs they rejected it and gave some changes to implement, but now after some work their suggestions have been implemented and now the plugin is in pretty good shape for a second round.

Anyone closely involved with Godot's development (pinging @reduz @vnen @akien-mga @Calinou) willing to submit it to the Blender devs? Preferably someone patient, as from what I've seen from @reduz's thread on the Blender mailing lists they can be picky, and it'd be the best for everyone involved (including other engines) if BCE got merged into Blender and their devs contributed to it.

**Comment by vnen** [comment]
Well, I don't use Blender (don't even have it installed), so I don't think I'm a good candidate for this.

I know you already put quite some effort into the code, but IMO you can be the one proposing that for the Blender devs. If you can't be the one, then we need to find someone else acquainted with the Collada Exporter code to discuss and implement changes if needed.

If you (or anyone else) need support from official voices, I'm pretty sure that @reduz or @akien-mga will help where they can.

**Comment by paper-pauper** [comment]
Thanks for answering, @vnen.

I'm honored to be even considered to do this but to be honest, I'm not the right person. I was glad to contribute and I'd be glad to contribute more *code* if needed, but I have to respectfully decline, as I don't have enough time to properly see it through.

Otherwise, since he was so kind to [post the original](https://developer.blender.org/D1787), I would kindly ask @ideasman42 to submit it to the Blender team again (I'm sure @reduz is fine with it).

**Comment by set-killer** [comment]
LOL, Nobody wants to get nagget about some minor code quality issues from those godlike developers. I suggest that we just create a tarball and throw it at them. Or we may create a floppy disk and send it to Amsterdam.

Anyway. The code of this plugin is public and everyone can modify it or distribute it. We may just notify them about the new code improvements based on their remarks and they can integrate it with the mainline blender OR they may open new issues or even merge requests... Everything here is public. From the community - to the community. If the blender devs decide that their project and community will benefit from this plugin we will be happy if they merge it. Otherwise nobody wants to read "spicy comments"...

However i don't expect that they will require new major changes in case that there was already discussion about the most important issues. 

Peace!

**Comment by set-killer** [comment]
Anybody?!?

The person who volunteers for this dirty job will be honoured with the title"Senior Negotiator" or "Ambassador of Blenderlands". 

@paper-pauper - you have right set of skills for this job. I'm sure will do a great job.

**Comment by paper-pauper** [comment]
@set-killer Calling people out after they refused is not cool, dude :unamused: 

If anything code-wise comes up, I might give a hand, but this is not my stuff. If a discussion springs up, I might say the wrong thing and frankly, after the response @reduz received on their mailing lists, I don't think I could do any better.

**Comment by reduz** [comment]
I get angry at them easily, we need someone who can keep it cool

**Comment by akien-mga** [comment]
@SaracenOne Interested? :P

**Comment by gau-veldt** [comment]
Sounds like getting something into Blender involves as much politics as it does code.

**Comment by ideasman42** [comment]
Hi, I did the initial review, there were 4 blocking issues getting this exporter into Blender:
See link: https://developer.blender.org/D1787#40477

@reduz complicated things considerably by requiring requiring the other exporter be removed, as a condition of making fixes.
See: https://developer.blender.org/D1787#40771

I'm no longer maintainer of this area of Blender, but in future - suggest to allow maintainers of the software to manage phasing out old features, which was the intention by all involved anyway... becoming picky with *how* a feature is phased out just makes it hard to accept changes, risking delays in the review process - which is whats happened here.

**Comment by paper-pauper** [comment]
@ideasman42 Thank you for your reply. Could you please tell us who's in charge of this now, so that we can contact him/her?

**Comment by ideasman42** [comment]
@paper-pauper, not sure. Best just post any updates to https://developer.blender.org/D1787 - if there is no response ping https://lists.blender.org/mailman/listinfo/bf-committers mailing list.

**Comment by paper-pauper** [comment]
Continuing the conversation from #33 - @set-killer have you found the Collada script Blender is supposed to be using in their repo?

**Comment by set-killer** [comment]
Ugh, no. But as far as i know the Blender release 2.8 is not going to happen any time soon. Maybe in the next year (I am not sure how far are they from this milestone, I found only some proposals). Also the first versions of 2.8X are going to be alphas and betas - not intended for production.

According to [this page](https://code.blender.org/2015/07/blender-2-8-the-workflow-release/) the releases 2.77, 2.78 and 2.79 are going to be bugfixes and small stable features. We just missed the 2.78 release. So if we submit it now we may end up in 2.79 but in that case we don;t know if they are going to backmerge it to their 2.8 branch.

**Comment by akien-mga** [comment]
Looks like Blender devs have their own plans already: https://code.blender.org/2016/10/the-collada-case/

Given the history, I guess we don't need to spend too much time fighting our way to upstream if on a blog post about their collada exporter they don't even mention the "Better Collada" one.

Also @reduz mentioned that once both Blender and Godot have PBR (a.k.a. quite soon), we could just write a plugin that exports directly to .tscn and thus bypass the need to use Collada.

**Comment by paper-pauper** [comment]
@akien-mga Could you please expand on the Physically Based Rendering thing? How does it bypass the need for Collada?

**Comment by akien-mga** [comment]
@paper-pauper I'm just paraphrasing @reduz, see the logs of the dev channel yesterday:
- http://godot.eska.me/irc-logs/devel/2016-10-24.log (from 23:00 CEST)
- http://godot.eska.me/irc-logs/devel/2016-10-25.log (first 4 lines)

**Comment by set-killer** [comment]
I think that the above statement wouldn't work that easily if Blender support PBR only for Cycles renderer (where everything is nodes).

**Comment by reduz** [comment]
I am closer to giving up and turning better collada into a .tscn exporter

**Comment by paper-pauper** [comment]
@reduz What about this: you move on to .tscn, meanwhile we try to get the Blender devs take a look at BCE. If they become the maintainers, good; if you don't, well, Godot can't be held back by third parties.

Is there some spec for the .tcsn format, by the way?

**Comment by set-killer** [comment]
@reduz :
According to [this document](https://code.blender.org/2016/09/blender-2-8-viewport-development/) the blenders PBR will be supported only for Cycles render. Which is kind of expected since currently only Cycles is in active development.

The Cycles renderer uses totally different organization for the objects properties like the diffuse colours, textures, speculars, normals and etc., related to the materials. In fact those properties are translated into node trees. That means when exporting the materials - all the material node trees (with all types of nodes) should be parsed. Blender has really really a lot of node types, some of which may not have analogue in Godot. Exporting something from the Cycles render is *madness!*

When you have objects made in the old Blender Render you cannot switch with one click to the Cycles Render. You have to redo all the materials, textures, shading and etc in Cycles.

> Is there some spec for the .tcsn format, by the way?

Exactly! We don't have a 500 pages fat PDF with the specification of tscn.

**Comment by paper-pauper** [comment]
@set-killer Where did you read that it's Cycles only?

> Real-time (GLSL/PBR) with scene lights
> Real-time (GLSL/PBR) with HDRI

Real-time means the Blender Internal renderer, doesn't it?

**Comment by paper-pauper** [comment]
It seems that a Blender dev just addressed BCE:

https://code.blender.org/2016/10/the-collada-case/#comment-75926

What to make of it?

**Comment by akien-mga** [comment]
> What to make of it?

That the communication was quite bad on both sides last time Godot devs and Blender devs discussed it :p

About Gaia's question regarding who would maintain the exporter, I think the intention on our side is to get it *upstreamed*, and thus that they would take it over fully, so that we can tell Godot users to just use the official Blender exporter. So the main point is whether the current exporter is useful to them, and if they want to use it as a base, write an importer in python (we have on in C++, but Godot-specific - though it can be used as a reference) and integrate it into Blender.

Whether the current Blender exporter should be obsoleted, that's for Blender devs to decide. @reduz likely expressed in the past his opinion about this existing exporter, and it might very well have been "better drop it as it produces unusable Collada" - given the blog post, I guess Blender devs have finally come to a similar conclusion and are now looking into alternative. "Better Collada" is there for the taking.

**Comment by set-killer** [comment]
@paper-pauper 
>(iii) We intend to retire Blender Internal as a standalone offline renderer, and make the real-time 
>viewport take over its duties. We plan to support its material system and convert existing Blender files 
>relying on the old engine to their OpenGL equivalent shaders seamlessly whenever possible.

In fact we don't know yet how is going to look the new python interface for accessing the object's properties.

**Comment by set-killer** [comment]
@reduz 
In the Collada format there is an ```<extra>``` tag which could be useful for the non-standard attributes like PBR settings. More info on [Page 75](https://www.khronos.org/files/collada_spec_1_5.pdf).

**Comment by reduz** [comment]
I know, but if we are exportig for godot, lets just export for godot then

**Comment by juan-garcia-m** [comment]
@reduz so what happened with the .tscn exporter?
I am working on a building tool for Godot 3.0+ for wich generate the DAE files from .blend, but a direct exporter will be much more appreciated.

**Comment by rminderhoud** [comment]
IMO this issue and #42 should both be closed and the goal should be to deprecate the Blender -> Collada -> Godot pipeline at some point. The best path would be to directly support Godot in an exporter (e.g. `.tscn`) but if an intermediary format is still required then GLTF 2.0 should be preferred over Collada (https://godotengine.org/article/we-should-all-use-gltf-20-export-3d-assets-game-engines)

**Comment by ideasman42** [comment]
+1 from Blender side, GLTF has a narrow scope which is less trouble to support, also a better fit for exporting to engines.

**Comment by akien-mga** [comment]
Agreed, that ship has sailed and we also want to promote glTF 2.0 has recommended exchange format. We'll take lengths to ensure that the output from Blender's official exporter can be used out of the box in Godot.
