### ISSUE TITLE
keyframe every frame

### ISSUE THREAD

**Issue by josesoplar** [godotengine/collada-exporter#76]
My blender object has key-frames every 4 frames, 
but when i export a 33 frame animation, I get 33 key-frames, rather than 9.
I have tried blender version 2.78 and 2.79b.

**Comment by gregeryb** [comment]
That's just how the exporter works, a keyframe is generated for every frame on the global timeline. This has to happen as the exporter exports only linearly interpolated animations but Blender is capable of quadratic/Bezier/wave... animation curves. So the timeline has to be oversampled otherwise for e.g. a sinewave animation curve would turn into an abrupt sawtooth curve. 
If you want to expert only 9 frames then work with a 9 frame timeline and adjust the playback speed. E.g. cut out the 3 unused between frames and reduce playback speed to 25%.

**Comment by Calinou** [comment]
Indeed, this is intended when the animation curve isn't linear.
